"""core/memory/obsidian_bridge.py — Obsidian Subconscious Bridge

Obsidian = the 'subconscious mind':
  - Long-term knowledge graph
  - Human-readable markdown
  - Wikilinks create associations between ideas
  - Survives everything — it's just files

How it works:
  1. Agent makes a decision → write to Obsidian vault
  2. Agent learns a pattern → write to Obsidian vault
  3. When recalling → scan relevant .md files
  4. The wikilinks create a knowledge graph the agent can traverse

Limitation: Obsidian must be installed separately by the user.
This bridge works with the vault directory directly (file system).
"""
from __future__ import annotations

import json
import re
import time
from datetime import datetime
from pathlib import Path
from typing import Optional


class ObsidianBridge:
    """
    Writes structured knowledge to an Obsidian vault.
    Reads back from it using file search.

    Vault structure created by this bridge:
      vault/
        _decisions/     ← every major decision
        _patterns/      ← learned patterns
        _projects/      ← per-project knowledge
        _daily/         ← daily activity logs
        _index.md       ← master index with all wikilinks
    """

    def __init__(self, vault_path: str = ""):
        self.vault = Path(vault_path or "obsidian_vault")
        self._init_vault()

    def _init_vault(self) -> None:
        """Create vault directory structure."""
        for folder in ["_decisions", "_patterns", "_projects", "_daily", "_lessons"]:
            (self.vault / folder).mkdir(parents=True, exist_ok=True)

        # Create index if not exists
        index_path = self.vault / "_index.md"
        if not index_path.exists():
            index_path.write_text(
                "# AI Agent Knowledge Graph\n\n"
                "Auto-generated by the AI Agent. Do not delete.\n\n"
                "## Sections\n"
                "- [[_decisions/README|Decisions]]\n"
                "- [[_patterns/README|Patterns]]\n"
                "- [[_projects/README|Projects]]\n"
                "- [[_lessons/README|Lessons Learned]]\n",
                encoding="utf-8",
            )

    # ─────────────────────────────────────────
    #  Write operations
    # ─────────────────────────────────────────
    def write_decision(
        self,
        title: str,
        decision: str,
        reasoning: str,
        factors: list[str],
        alternatives: list[str],
        outcome: str = "",
        project: str = "",
    ) -> str:
        """Write a decision to the Obsidian vault. Returns file path."""
        date_str = datetime.now().strftime("%Y-%m-%d")
        time_str = datetime.now().strftime("%H:%M")
        slug = self._slugify(title)
        filename = f"{date_str}_{slug}.md"
        path = self.vault / "_decisions" / filename

        # Build markdown with wikilinks
        related_links = ""
        if project:
            related_links += f"\n- [[_projects/{self._slugify(project)}|{project}]]"

        content = f"""---
type: decision
date: {date_str}
time: {time_str}
project: {project or "general"}
status: {"resolved" if outcome else "pending"}
---

# Decision: {title}

## What was decided
{decision}

## Why this decision was made
{reasoning}

## Factors that influenced this
{self._to_bullets(factors)}

## Alternatives considered
{self._to_bullets(alternatives) if alternatives else "None documented"}

## Outcome
{outcome or "_Not yet known_"}

## Related
{related_links or "_None_"}

---
*Logged at {time_str} on {date_str}*
"""
        path.write_text(content, encoding="utf-8")
        self._update_index("_decisions", title, filename)
        return str(path)

    def write_pattern(
        self,
        pattern_name: str,
        description: str,
        when_to_use: str,
        when_to_avoid: str,
        examples: list[str],
        confidence: float = 0.7,
    ) -> str:
        """Write a learned pattern — something that works reliably."""
        slug = self._slugify(pattern_name)
        path = self.vault / "_patterns" / f"{slug}.md"

        content = f"""---
type: pattern
confidence: {confidence:.2f}
last_updated: {datetime.now().strftime("%Y-%m-%d")}
---

# Pattern: {pattern_name}

## Description
{description}

## When to use
{when_to_use}

## When to avoid
{when_to_avoid}

## Examples
{self._to_bullets(examples)}

## Confidence
{confidence:.0%} — {"High confidence, use freely" if confidence > 0.8 else "Moderate, verify before using" if confidence > 0.5 else "Low, treat as hypothesis"}

---
*Pattern learned from observed behavior*
"""
        path.write_text(content, encoding="utf-8")
        self._update_index("_patterns", pattern_name, f"{slug}.md")
        return str(path)

    def write_lesson(
        self,
        what_happened: str,
        what_went_wrong: str,
        what_to_do_differently: str,
        tags: Optional[list[str]] = None,
    ) -> str:
        """Write a lesson learned — mistakes and corrections."""
        date_str = datetime.now().strftime("%Y-%m-%d")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        path = self.vault / "_lessons" / f"lesson_{timestamp}.md"

        tags_str = " ".join(f"#{t}" for t in (tags or []))

        content = f"""---
type: lesson
date: {date_str}
tags: {tags or []}
---

# Lesson: {date_str}

{tags_str}

## What happened
{what_happened}

## What went wrong
{what_went_wrong}

## What to do differently next time
{what_to_do_differently}

---
*Every mistake is a data point.*
"""
        path.write_text(content, encoding="utf-8")
        return str(path)

    def log_daily(self, summary: str, decisions_made: int, tools_used: list[str]) -> None:
        """Daily activity log — append to today's note."""
        date_str = datetime.now().strftime("%Y-%m-%d")
        path = self.vault / "_daily" / f"{date_str}.md"

        if not path.exists():
            path.write_text(f"# Daily Log — {date_str}\n\n", encoding="utf-8")

        with open(path, "a", encoding="utf-8") as f:
            f.write(
                f"\n## {datetime.now().strftime('%H:%M')}\n"
                f"{summary}\n"
                f"- Decisions made: {decisions_made}\n"
                f"- Tools used: {', '.join(tools_used) or 'none'}\n"
            )

    # ─────────────────────────────────────────
    #  Read operations
    # ─────────────────────────────────────────
    def search(self, query: str, max_results: int = 5) -> list[dict]:
        """Search vault for relevant notes."""
        query_words = set(query.lower().split())
        results = []

        for md_file in self.vault.rglob("*.md"):
            if md_file.name.startswith("_index"):
                continue
            try:
                content = md_file.read_text(encoding="utf-8")
                content_lower = content.lower()

                # Simple relevance: count matching query words
                hits = sum(1 for w in query_words if w in content_lower)
                if hits > 0:
                    # Extract first non-header line as preview
                    lines = [l for l in content.split("\n") if l.strip() and not l.startswith("#")]
                    preview = lines[0][:120] if lines else ""
                    results.append({
                        "file": str(md_file.relative_to(self.vault)),
                        "relevance": hits,
                        "preview": preview,
                        "type": str(md_file.parent.name).lstrip("_"),
                    })
            except Exception:
                continue

        results.sort(key=lambda r: r["relevance"], reverse=True)
        return results[:max_results]

    def get_recent_decisions(self, n: int = 10) -> list[dict]:
        """Get the N most recent decisions."""
        decisions_dir = self.vault / "_decisions"
        files = sorted(decisions_dir.glob("*.md"), reverse=True)[:n]

        results = []
        for f in files:
            try:
                content = f.read_text(encoding="utf-8")
                # Extract title
                title_match = re.search(r"# Decision: (.+)", content)
                title = title_match.group(1) if title_match else f.stem
                # Extract date from frontmatter
                date_match = re.search(r"date: (.+)", content)
                date = date_match.group(1) if date_match else "unknown"
                results.append({"title": title, "date": date, "file": f.name})
            except Exception:
                continue
        return results

    def get_patterns(self) -> list[dict]:
        """Get all learned patterns."""
        patterns_dir = self.vault / "_patterns"
        results = []
        for f in patterns_dir.glob("*.md"):
            try:
                content = f.read_text(encoding="utf-8")
                title_match = re.search(r"# Pattern: (.+)", content)
                conf_match = re.search(r"confidence: ([\d.]+)", content)
                results.append({
                    "name": title_match.group(1) if title_match else f.stem,
                    "confidence": float(conf_match.group(1)) if conf_match else 0.5,
                    "file": f.name,
                })
            except Exception:
                continue
        return sorted(results, key=lambda p: p["confidence"], reverse=True)

    def get_stats(self) -> dict:
        """Return hit rate, miss count, eviction count, and current size."""
        return {
            "vault_path": str(self.vault),
            "decisions": len(list((self.vault / "_decisions").glob("*.md"))),
            "patterns": len(list((self.vault / "_patterns").glob("*.md"))),
            "lessons": len(list((self.vault / "_lessons").glob("*.md"))),
            "daily_logs": len(list((self.vault / "_daily").glob("*.md"))),
        }

    # ─────────────────────────────────────────
    #  Helpers
    # ─────────────────────────────────────────
    def _update_index(self, section: str, title: str, filename: str) -> None:
        """Add a wikilink to the section's README."""
        readme = self.vault / section / "README.md"
        link = f"- [[{filename}|{title}]]\n"
        if not readme.exists():
            readme.write_text(f"# {section.lstrip('_').title()}\n\n", encoding="utf-8")
        with open(readme, "a", encoding="utf-8") as f:
            f.write(link)

    @staticmethod
    def _slugify(text: str) -> str:
        slug = re.sub(r"[^\w\s-]", "", text.lower())
        return re.sub(r"[-\s]+", "_", slug).strip("_")[:50]

    @staticmethod
    def _to_bullets(items: list[str]) -> str:
        return "\n".join(f"- {item}" for item in items) if items else "_None_"


# Singleton
_obsidian: Optional[ObsidianBridge] = None

def get_obsidian_bridge(vault_path: str = "") -> ObsidianBridge:
    """Get obsidian bridge."""
    global _obsidian
    if _obsidian is None:
        _obsidian = ObsidianBridge(vault_path)
    return _obsidian
